// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.e9.framework.handler.codec.protobuf.message;

public final class HelloWorldRequest {
  private HelloWorldRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HelloWorldOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 Total_Length = 1;
    /**
     * <code>repeated int32 Total_Length = 1;</code>
     */
    java.util.List<java.lang.Integer> getTotalLengthList();
    /**
     * <code>repeated int32 Total_Length = 1;</code>
     */
    int getTotalLengthCount();
    /**
     * <code>repeated int32 Total_Length = 1;</code>
     */
    int getTotalLength(int index);

    // repeated int32 Command_Id = 2;
    /**
     * <code>repeated int32 Command_Id = 2;</code>
     */
    java.util.List<java.lang.Integer> getCommandIdList();
    /**
     * <code>repeated int32 Command_Id = 2;</code>
     */
    int getCommandIdCount();
    /**
     * <code>repeated int32 Command_Id = 2;</code>
     */
    int getCommandId(int index);

    // repeated int32 Sequence_Id = 3;
    /**
     * <code>repeated int32 Sequence_Id = 3;</code>
     */
    java.util.List<java.lang.Integer> getSequenceIdList();
    /**
     * <code>repeated int32 Sequence_Id = 3;</code>
     */
    int getSequenceIdCount();
    /**
     * <code>repeated int32 Sequence_Id = 3;</code>
     */
    int getSequenceId(int index);

    // repeated string name = 4;
    /**
     * <code>repeated string name = 4;</code>
     */
    java.util.List<java.lang.String>
    getNameList();
    /**
     * <code>repeated string name = 4;</code>
     */
    int getNameCount();
    /**
     * <code>repeated string name = 4;</code>
     */
    java.lang.String getName(int index);
    /**
     * <code>repeated string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes(int index);

    // optional string txt = 5;
    /**
     * <code>optional string txt = 5;</code>
     */
    boolean hasTxt();
    /**
     * <code>optional string txt = 5;</code>
     */
    java.lang.String getTxt();
    /**
     * <code>optional string txt = 5;</code>
     */
    com.google.protobuf.ByteString
        getTxtBytes();
  }
  /**
   * Protobuf type {@code test.HelloWorld}
   */
  public static final class HelloWorld extends
      com.google.protobuf.GeneratedMessage
      implements HelloWorldOrBuilder {
    // Use HelloWorld.newBuilder() to construct.
    private HelloWorld(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HelloWorld(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HelloWorld defaultInstance;
    public static HelloWorld getDefaultInstance() {
      return defaultInstance;
    }

    public HelloWorld getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HelloWorld(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                totalLength_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              totalLength_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                totalLength_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                totalLength_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                commandId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              commandId_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                commandId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                commandId_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sequenceId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              sequenceId_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                sequenceId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                sequenceId_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                name_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              name_.add(input.readBytes());
              break;
            }
            case 42: {
              bitField0_ |= 0x00000001;
              txt_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          totalLength_ = java.util.Collections.unmodifiableList(totalLength_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          commandId_ = java.util.Collections.unmodifiableList(commandId_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sequenceId_ = java.util.Collections.unmodifiableList(sequenceId_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          name_ = new com.google.protobuf.UnmodifiableLazyStringList(name_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.internal_static_test_HelloWorld_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.internal_static_test_HelloWorld_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld.class, com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld.Builder.class);
    }

    public static com.google.protobuf.Parser<HelloWorld> PARSER =
        new com.google.protobuf.AbstractParser<HelloWorld>() {
      public HelloWorld parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloWorld(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HelloWorld> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated int32 Total_Length = 1;
    public static final int TOTAL_LENGTH_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> totalLength_;
    /**
     * <code>repeated int32 Total_Length = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getTotalLengthList() {
      return totalLength_;
    }
    /**
     * <code>repeated int32 Total_Length = 1;</code>
     */
    public int getTotalLengthCount() {
      return totalLength_.size();
    }
    /**
     * <code>repeated int32 Total_Length = 1;</code>
     */
    public int getTotalLength(int index) {
      return totalLength_.get(index);
    }

    // repeated int32 Command_Id = 2;
    public static final int COMMAND_ID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> commandId_;
    /**
     * <code>repeated int32 Command_Id = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getCommandIdList() {
      return commandId_;
    }
    /**
     * <code>repeated int32 Command_Id = 2;</code>
     */
    public int getCommandIdCount() {
      return commandId_.size();
    }
    /**
     * <code>repeated int32 Command_Id = 2;</code>
     */
    public int getCommandId(int index) {
      return commandId_.get(index);
    }

    // repeated int32 Sequence_Id = 3;
    public static final int SEQUENCE_ID_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> sequenceId_;
    /**
     * <code>repeated int32 Sequence_Id = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getSequenceIdList() {
      return sequenceId_;
    }
    /**
     * <code>repeated int32 Sequence_Id = 3;</code>
     */
    public int getSequenceIdCount() {
      return sequenceId_.size();
    }
    /**
     * <code>repeated int32 Sequence_Id = 3;</code>
     */
    public int getSequenceId(int index) {
      return sequenceId_.get(index);
    }

    // repeated string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList name_;
    /**
     * <code>repeated string name = 4;</code>
     */
    public java.util.List<java.lang.String>
        getNameList() {
      return name_;
    }
    /**
     * <code>repeated string name = 4;</code>
     */
    public int getNameCount() {
      return name_.size();
    }
    /**
     * <code>repeated string name = 4;</code>
     */
    public java.lang.String getName(int index) {
      return name_.get(index);
    }
    /**
     * <code>repeated string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes(int index) {
      return name_.getByteString(index);
    }

    // optional string txt = 5;
    public static final int TXT_FIELD_NUMBER = 5;
    private java.lang.Object txt_;
    /**
     * <code>optional string txt = 5;</code>
     */
    public boolean hasTxt() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string txt = 5;</code>
     */
    public java.lang.String getTxt() {
      java.lang.Object ref = txt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          txt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string txt = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTxtBytes() {
      java.lang.Object ref = txt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      totalLength_ = java.util.Collections.emptyList();
      commandId_ = java.util.Collections.emptyList();
      sequenceId_ = java.util.Collections.emptyList();
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      txt_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < totalLength_.size(); i++) {
        output.writeInt32(1, totalLength_.get(i));
      }
      for (int i = 0; i < commandId_.size(); i++) {
        output.writeInt32(2, commandId_.get(i));
      }
      for (int i = 0; i < sequenceId_.size(); i++) {
        output.writeInt32(3, sequenceId_.get(i));
      }
      for (int i = 0; i < name_.size(); i++) {
        output.writeBytes(4, name_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(5, getTxtBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < totalLength_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(totalLength_.get(i));
        }
        size += dataSize;
        size += 1 * getTotalLengthList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < commandId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(commandId_.get(i));
        }
        size += dataSize;
        size += 1 * getCommandIdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sequenceId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(sequenceId_.get(i));
        }
        size += dataSize;
        size += 1 * getSequenceIdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < name_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(name_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getNameList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTxtBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.HelloWorld}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.internal_static_test_HelloWorld_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.internal_static_test_HelloWorld_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld.class, com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld.Builder.class);
      }

      // Construct using com.e9.tcp.gateway.private_protocol.HelloWorldRequest.HelloWorld.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        totalLength_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        commandId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        sequenceId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        txt_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.internal_static_test_HelloWorld_descriptor;
      }

      public com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld getDefaultInstanceForType() {
        return com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld.getDefaultInstance();
      }

      public com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld build() {
        com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld buildPartial() {
        com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld result = new com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          totalLength_ = java.util.Collections.unmodifiableList(totalLength_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.totalLength_ = totalLength_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          commandId_ = java.util.Collections.unmodifiableList(commandId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.commandId_ = commandId_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          sequenceId_ = java.util.Collections.unmodifiableList(sequenceId_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.sequenceId_ = sequenceId_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          name_ = new com.google.protobuf.UnmodifiableLazyStringList(
              name_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000001;
        }
        result.txt_ = txt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld) {
          return mergeFrom((com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld other) {
        if (other == com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld.getDefaultInstance()) return this;
        if (!other.totalLength_.isEmpty()) {
          if (totalLength_.isEmpty()) {
            totalLength_ = other.totalLength_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTotalLengthIsMutable();
            totalLength_.addAll(other.totalLength_);
          }
          onChanged();
        }
        if (!other.commandId_.isEmpty()) {
          if (commandId_.isEmpty()) {
            commandId_ = other.commandId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCommandIdIsMutable();
            commandId_.addAll(other.commandId_);
          }
          onChanged();
        }
        if (!other.sequenceId_.isEmpty()) {
          if (sequenceId_.isEmpty()) {
            sequenceId_ = other.sequenceId_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSequenceIdIsMutable();
            sequenceId_.addAll(other.sequenceId_);
          }
          onChanged();
        }
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
        if (other.hasTxt()) {
          bitField0_ |= 0x00000010;
          txt_ = other.txt_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.e9.framework.handler.codec.protobuf.message.HelloWorldRequest.HelloWorld) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 Total_Length = 1;
      private java.util.List<java.lang.Integer> totalLength_ = java.util.Collections.emptyList();
      private void ensureTotalLengthIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          totalLength_ = new java.util.ArrayList<java.lang.Integer>(totalLength_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 Total_Length = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getTotalLengthList() {
        return java.util.Collections.unmodifiableList(totalLength_);
      }
      /**
       * <code>repeated int32 Total_Length = 1;</code>
       */
      public int getTotalLengthCount() {
        return totalLength_.size();
      }
      /**
       * <code>repeated int32 Total_Length = 1;</code>
       */
      public int getTotalLength(int index) {
        return totalLength_.get(index);
      }
      /**
       * <code>repeated int32 Total_Length = 1;</code>
       */
      public Builder setTotalLength(
          int index, int value) {
        ensureTotalLengthIsMutable();
        totalLength_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 Total_Length = 1;</code>
       */
      public Builder addTotalLength(int value) {
        ensureTotalLengthIsMutable();
        totalLength_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 Total_Length = 1;</code>
       */
      public Builder addAllTotalLength(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTotalLengthIsMutable();
        super.addAll(values, totalLength_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 Total_Length = 1;</code>
       */
      public Builder clearTotalLength() {
        totalLength_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated int32 Command_Id = 2;
      private java.util.List<java.lang.Integer> commandId_ = java.util.Collections.emptyList();
      private void ensureCommandIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          commandId_ = new java.util.ArrayList<java.lang.Integer>(commandId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 Command_Id = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getCommandIdList() {
        return java.util.Collections.unmodifiableList(commandId_);
      }
      /**
       * <code>repeated int32 Command_Id = 2;</code>
       */
      public int getCommandIdCount() {
        return commandId_.size();
      }
      /**
       * <code>repeated int32 Command_Id = 2;</code>
       */
      public int getCommandId(int index) {
        return commandId_.get(index);
      }
      /**
       * <code>repeated int32 Command_Id = 2;</code>
       */
      public Builder setCommandId(
          int index, int value) {
        ensureCommandIdIsMutable();
        commandId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 Command_Id = 2;</code>
       */
      public Builder addCommandId(int value) {
        ensureCommandIdIsMutable();
        commandId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 Command_Id = 2;</code>
       */
      public Builder addAllCommandId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCommandIdIsMutable();
        super.addAll(values, commandId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 Command_Id = 2;</code>
       */
      public Builder clearCommandId() {
        commandId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // repeated int32 Sequence_Id = 3;
      private java.util.List<java.lang.Integer> sequenceId_ = java.util.Collections.emptyList();
      private void ensureSequenceIdIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sequenceId_ = new java.util.ArrayList<java.lang.Integer>(sequenceId_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 Sequence_Id = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getSequenceIdList() {
        return java.util.Collections.unmodifiableList(sequenceId_);
      }
      /**
       * <code>repeated int32 Sequence_Id = 3;</code>
       */
      public int getSequenceIdCount() {
        return sequenceId_.size();
      }
      /**
       * <code>repeated int32 Sequence_Id = 3;</code>
       */
      public int getSequenceId(int index) {
        return sequenceId_.get(index);
      }
      /**
       * <code>repeated int32 Sequence_Id = 3;</code>
       */
      public Builder setSequenceId(
          int index, int value) {
        ensureSequenceIdIsMutable();
        sequenceId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 Sequence_Id = 3;</code>
       */
      public Builder addSequenceId(int value) {
        ensureSequenceIdIsMutable();
        sequenceId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 Sequence_Id = 3;</code>
       */
      public Builder addAllSequenceId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSequenceIdIsMutable();
        super.addAll(values, sequenceId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 Sequence_Id = 3;</code>
       */
      public Builder clearSequenceId() {
        sequenceId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // repeated string name = 4;
      private com.google.protobuf.LazyStringList name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          name_ = new com.google.protobuf.LazyStringArrayList(name_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string name = 4;</code>
       */
      public java.util.List<java.lang.String>
          getNameList() {
        return java.util.Collections.unmodifiableList(name_);
      }
      /**
       * <code>repeated string name = 4;</code>
       */
      public int getNameCount() {
        return name_.size();
      }
      /**
       * <code>repeated string name = 4;</code>
       */
      public java.lang.String getName(int index) {
        return name_.get(index);
      }
      /**
       * <code>repeated string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes(int index) {
        return name_.getByteString(index);
      }
      /**
       * <code>repeated string name = 4;</code>
       */
      public Builder setName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 4;</code>
       */
      public Builder addName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 4;</code>
       */
      public Builder addAllName(
          java.lang.Iterable<java.lang.String> values) {
        ensureNameIsMutable();
        super.addAll(values, name_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 4;</code>
       */
      public Builder clearName() {
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 4;</code>
       */
      public Builder addNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }

      // optional string txt = 5;
      private java.lang.Object txt_ = "";
      /**
       * <code>optional string txt = 5;</code>
       */
      public boolean hasTxt() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string txt = 5;</code>
       */
      public java.lang.String getTxt() {
        java.lang.Object ref = txt_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          txt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string txt = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTxtBytes() {
        java.lang.Object ref = txt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string txt = 5;</code>
       */
      public Builder setTxt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        txt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string txt = 5;</code>
       */
      public Builder clearTxt() {
        bitField0_ = (bitField0_ & ~0x00000010);
        txt_ = getDefaultInstance().getTxt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string txt = 5;</code>
       */
      public Builder setTxtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        txt_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.HelloWorld)
    }

    static {
      defaultInstance = new HelloWorld(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.HelloWorld)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_HelloWorld_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_HelloWorld_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTest.proto\022\004test\"f\n\nHelloWorld\022\024\n\014Tota" +
      "l_Length\030\001 \003(\005\022\022\n\nCommand_Id\030\002 \003(\005\022\023\n\013Se" +
      "quence_Id\030\003 \003(\005\022\014\n\004name\030\004 \003(\t\022\013\n\003txt\030\005 \001" +
      "(\tB8\n#com.e9.tcp.gateway.private_protoco" +
      "lB\021HelloWorldRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_test_HelloWorld_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_test_HelloWorld_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_HelloWorld_descriptor,
              new java.lang.String[] { "TotalLength", "CommandId", "SequenceId", "Name", "Txt", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
